#ifndef APP_NET_MESH_CONFIG_H_
#define APP_NET_MESH_CONFIG_H_

#ifndef NET_MESH_LPN
#	define NET_MESH_LPN							0
#endif

//#ifndef NET_MESH_FRIEND
//#	define NET_MESH_FRIEND						0
//#endif

#if NET_MESH_LPN && NET_MESH_FRIEND
#	error "Node can't be LPN and FRIEND"
#endif

#ifndef NET_MESH_GENERIC_ONOFF_SERVER
#	define NET_MESH_GENERIC_ONOFF_SERVER 		0
#endif
#ifndef NET_MESH_GENERIC_LEVEL_SERVER
#	define NET_MESH_GENERIC_LEVEL_SERVER 		0
#endif
#ifndef NET_MESH_SENSOR_SERVER
#	define NET_MESH_SENSOR_SERVER 				0
#endif
#ifndef NET_MESH_VENDOR_SERVER
#	define NET_MESH_VENDOR_SERVER 				0
#endif

#ifndef NET_MESH_GENERIC_ONOFF_CLIENT
#	define NET_MESH_GENERIC_ONOFF_CLIENT 		0
#endif
#ifndef NET_MESH_GENERIC_LEVEL_CLIENT
#	define NET_MESH_GENERIC_LEVEL_CLIENT 		0
#endif
#ifndef NET_MESH_SENSOR_CLIENT
#	define NET_MESH_SENSOR_CLIENT 				0
#endif
#ifndef NET_MESH_VENDOR_CLIENT
#	define NET_MESH_VENDOR_CLIENT 				0
#endif
#ifndef NET_MESH_LIGHT_LIGHTNESS_CLIENT
#	define NET_MESH_LIGHT_LIGHTNESS_CLIENT		0
#endif


#define NET_MESH_LPN_FRIEND_FIND_RETRY_MS		10000
#define NET_MESH_LPN_POLL_MS					60000
#define NET_MESH_LPN_POLL_QUEUE_LEN				4
#ifndef NET_MESH_TRANSACTION_TIMEOUT_MS
#define NET_MESH_TRANSACTION_TIMEOUT_MS			100
#endif
#ifndef NET_MESH_TRANSACTION_RETRIES
#	define NET_MESH_TRANSACTION_RETRIES			0
#endif

#endif /* APP_NET_MESH_CONFIG_H_ */
